build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.14
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  CLI_VERSION: 4.14.0
  LIBWEBSOCKETS_VERSION: 4.2.1
  TTYD_VERSION: 3e37e33b1cd927ae8f25cfbcf0da268723b6d230
