version: 1.0.0
slug: modbus
name: Modbus (USB local port)
description: This addon allows you to communicate local USB device with MQTT server.
url: https://github.com/45clouds/haos-addons/tree/master/modbus
advanced: false
arch:
  - amd64
audio: false
hassio_api: false
hassio_role: manager
host_dbus: true
ingress: false
init: false
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw
options:
  usbport: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  mqtthost: 10.0.255.10
  mqttuser: 
  mqttpassword: 
schema:
  usbport: str
  mqtthost: str
  mqttuser: str
  mqttpassword: password
startup: services
uart: true
